# Sample .travis.yml for R projects

language: R
warnings_are_errors: false
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

bioc_packages:
  - BiocStyle
  - GenomeInfoDb
  - IRanges
  - GenomicRanges

r_github_packages:
  - jimhester/covr

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::coveralls()'
